# Generated by Django 4.1.7 on 2023-05-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_eid'),
    ]

    operations = [
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantType', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('path', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'plant',
            },
        ),
    ]
